import { useEffect, useState } from 'react'
import type { Milestone, Project } from '../../types/domain'
import { getMilestones, removeMilestone, saveMilestone } from './trackerService'

export function MilestonesView({ project, isManager }: { project: Project; isManager: boolean }) {
  const [items, setItems] = useState<Milestone[]>([])
  const [error, setError] = useState<string | null>(null)
  const load = async () => setItems(await getMilestones(project.id))
  useEffect(() => { let active = true; void getMilestones(project.id).then((data) => { if (active) setItems(data) }).catch(() => { if (active) setError('Không tải được mốc kiểm soát.') }); return () => { active = false } }, [project.id])
  const change = (id: string, patch: Partial<Milestone>) => setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item))
  const saveAll = async () => { setError(null); try { await Promise.all(items.map((item, index) => saveMilestone(project.id, { ...item, sort_order: index }))); await load() } catch { setError('Không lưu được mốc kiểm soát.') } }
  const add = () => setItems((current) => [...current, { id: `new-${crypto.randomUUID()}`, project_id: project.id, name: 'Mốc kiểm soát mới', due_date: project.end_date || new Date().toISOString().slice(0, 10), condition_text: null, owner_text: null, achieved: false, achieved_at: null, sort_order: current.length }])
  return <><div className="ovhead"><div><div className="crumb"><button>{project.name}</button><span>›</span><span>Mốc kiểm soát</span></div><h1>Mốc kiểm soát</h1><p className="tiny muted">Các mốc được quản lý riêng trên web và hiển thị trên Gantt.</p></div>{isManager && <button className="btn pri" onClick={add}>+ Thêm mốc</button>}</div>{error && <div className="note warn offline">{error}</div>}<div className="stats"><div className="stat"><b>{items.length}</b><span>Mốc kiểm soát</span></div><div className="stat"><b>{items.filter((item) => item.achieved).length}</b><span>Đã đạt</span></div><div className="stat hi"><b>{items.filter((item) => !item.achieved && item.due_date < new Date().toISOString().slice(0, 10)).length}</b><span>Quá hạn</span></div></div><div className="card"><table className="mile"><thead><tr><th /><th>Mốc kiểm soát</th><th>Ngày phải đạt</th><th>Chủ trì</th><th>Điều kiện đạt</th><th>Trạng thái</th>{isManager && <th />}</tr></thead><tbody>{items.map((item, index) => <tr key={item.id}><td>{index + 1}</td><td>{isManager ? <input value={item.name} onChange={(event) => change(item.id, { name: event.target.value })} /> : item.name}</td><td>{isManager ? <input type="date" value={item.due_date} onChange={(event) => change(item.id, { due_date: event.target.value })} /> : date(item.due_date)}</td><td>{isManager ? <input value={item.owner_text ?? ''} onChange={(event) => change(item.id, { owner_text: event.target.value })} /> : item.owner_text || '—'}</td><td>{isManager ? <input value={item.condition_text ?? ''} onChange={(event) => change(item.id, { condition_text: event.target.value })} /> : item.condition_text || '—'}</td><td>{isManager ? <select value={item.achieved ? 'done' : 'open'} onChange={(event) => change(item.id, { achieved: event.target.value === 'done' })}><option value="open">Chưa đạt</option><option value="done">Đã đạt</option></select> : <span className={`pill ${item.achieved ? 'p-done' : item.due_date < new Date().toISOString().slice(0, 10) ? 'p-late' : 'p-todo'}`}><i />{item.achieved ? 'Đã đạt' : 'Chưa đạt'}</span>}</td>{isManager && <td><button className="btn dgr sm" onClick={() => { if (item.id.startsWith('new-')) setItems((current) => current.filter((candidate) => candidate.id !== item.id)); else if (window.confirm(`Xóa mốc ${item.name}?`)) void removeMilestone(item.id).then(load) }}>Xóa</button></td>}</tr>)}</tbody></table></div>{isManager && <div className="row2" style={{ marginTop: 10 }}><span className="tiny muted">Sửa trực tiếp trong bảng rồi bấm lưu.</span><button className="btn pri" onClick={() => void saveAll()}>Lưu thay đổi</button></div>}</>
}
function date(value: string) { return new Intl.DateTimeFormat('vi-VN').format(new Date(`${value}T00:00:00`)) }
